version: '3'
services:
  redis:
    image: redis:latest
    networks:
      default:
        aliases:
          - redis
    ports:
      - "0.0.0.0:6379:6379"

  maria:
    image: mariadb:latest
    networks:
      default:
        aliases:
          - maria
    restart: always
    command: --lower_case_table_names=1
    volumes:
       - /Users/ed/DB/mysql:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: 1qaz2wsxz
    ports:
      - "127.0.0.1:3306:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - "0.0.0.0:8888:8080"

  # frontend: # 前端的環境
  #   image: node:14.9.0
  #   volumes:
  #       - ./frontend:/code # 本機的./fronted連通到container的/code
  #   command: tail -F anything
  #   ports:
  #       - "8080:8080" # 本機的8080跟container的8080做連接

  # backend: # 後端的環境
  #   image: golang:1.15.1
  #   volumes:
  #       - .:/go/src/code
  #   command: tail -F anything
  #   ports:
  #       - "9090:9090"